# Generated by Django 3.1.5 on 2021-01-06 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='peep',
        ),
    ]
