# Generated by Django 3.1.5 on 2021-01-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_auto_20210106_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('marked_img', models.ImageField(upload_to='images/marked')),
                ('detected_object', models.CharField(max_length=200)),
            ],
        ),
    ]
